version: 2
jobs:
  build:
    docker:
     - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/kittymay.github.io
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bash automated_build.sh
